// Code generated by MockGen. DO NOT EDIT.
// Source: ai_service.go
//
// Generated by this command:
//
//	mockgen -source=ai_service.go -destination=mock/ai_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	service "gist/backend/internal/service"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAIService is a mock of AIService interface.
type MockAIService struct {
	ctrl     *gomock.Controller
	recorder *MockAIServiceMockRecorder
	isgomock struct{}
}

// MockAIServiceMockRecorder is the mock recorder for MockAIService.
type MockAIServiceMockRecorder struct {
	mock *MockAIService
}

// NewMockAIService creates a new mock instance.
func NewMockAIService(ctrl *gomock.Controller) *MockAIService {
	mock := &MockAIService{ctrl: ctrl}
	mock.recorder = &MockAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIService) EXPECT() *MockAIServiceMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockAIService) Analyze(ctx context.Context, entryID int64, content, title string, isReadability bool) (*model.AIAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, entryID, content, title, isReadability)
	ret0, _ := ret[0].(*model.AIAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockAIServiceMockRecorder) Analyze(ctx, entryID, content, title, isReadability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockAIService)(nil).Analyze), ctx, entryID, content, title, isReadability)
}

// ClearAllCache mocks base method.
func (m *MockAIService) ClearAllCache(ctx context.Context) (int64, int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAllCache", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// ClearAllCache indicates an expected call of ClearAllCache.
func (mr *MockAIServiceMockRecorder) ClearAllCache(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAllCache", reflect.TypeOf((*MockAIService)(nil).ClearAllCache), ctx)
}

// GetCachedSummary mocks base method.
func (m *MockAIService) GetCachedSummary(ctx context.Context, entryID int64, isReadability bool) (*model.AISummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedSummary", ctx, entryID, isReadability)
	ret0, _ := ret[0].(*model.AISummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedAnalysis mocks base method.
func (m *MockAIService) GetCachedAnalysis(ctx context.Context, entryID int64, isReadability bool) (*model.AIAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedAnalysis", ctx, entryID, isReadability)
	ret0, _ := ret[0].(*model.AIAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedAnalysis indicates an expected call of GetCachedAnalysis.
func (mr *MockAIServiceMockRecorder) GetCachedAnalysis(ctx, entryID, isReadability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedAnalysis", reflect.TypeOf((*MockAIService)(nil).GetCachedAnalysis), ctx, entryID, isReadability)
}

// GetCachedSummary indicates an expected call of GetCachedSummary.
func (mr *MockAIServiceMockRecorder) GetCachedSummary(ctx, entryID, isReadability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedSummary", reflect.TypeOf((*MockAIService)(nil).GetCachedSummary), ctx, entryID, isReadability)
}

// GetCachedTranslation mocks base method.
func (m *MockAIService) GetCachedTranslation(ctx context.Context, entryID int64, isReadability bool) (*model.AITranslation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedTranslation", ctx, entryID, isReadability)
	ret0, _ := ret[0].(*model.AITranslation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedTranslation indicates an expected call of GetCachedTranslation.
func (mr *MockAIServiceMockRecorder) GetCachedTranslation(ctx, entryID, isReadability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedTranslation", reflect.TypeOf((*MockAIService)(nil).GetCachedTranslation), ctx, entryID, isReadability)
}

// ListStoredAnalyses mocks base method.
func (m *MockAIService) ListStoredAnalyses(ctx context.Context, limit, offset int) ([]model.StoredAIAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoredAnalyses", ctx, limit, offset)
	ret0, _ := ret[0].([]model.StoredAIAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoredAnalyses indicates an expected call of ListStoredAnalyses.
func (mr *MockAIServiceMockRecorder) ListStoredAnalyses(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoredAnalyses", reflect.TypeOf((*MockAIService)(nil).ListStoredAnalyses), ctx, limit, offset)
}

// BuildDailyAnalysisReport mocks base method.
func (m *MockAIService) BuildDailyAnalysisReport(ctx context.Context, day time.Time) (*model.AIDailyReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildDailyAnalysisReport", ctx, day)
	ret0, _ := ret[0].(*model.AIDailyReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildDailyAnalysisReport indicates an expected call of BuildDailyAnalysisReport.
func (mr *MockAIServiceMockRecorder) BuildDailyAnalysisReport(ctx, day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildDailyAnalysisReport", reflect.TypeOf((*MockAIService)(nil).BuildDailyAnalysisReport), ctx, day)
}

// GetSummaryLanguage mocks base method.
func (m *MockAIService) GetSummaryLanguage(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummaryLanguage", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSummaryLanguage indicates an expected call of GetSummaryLanguage.
func (mr *MockAIServiceMockRecorder) GetSummaryLanguage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummaryLanguage", reflect.TypeOf((*MockAIService)(nil).GetSummaryLanguage), ctx)
}

// SaveSummary mocks base method.
func (m *MockAIService) SaveSummary(ctx context.Context, entryID int64, isReadability bool, summary string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSummary", ctx, entryID, isReadability, summary)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSummary indicates an expected call of SaveSummary.
func (mr *MockAIServiceMockRecorder) SaveSummary(ctx, entryID, isReadability, summary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSummary", reflect.TypeOf((*MockAIService)(nil).SaveSummary), ctx, entryID, isReadability, summary)
}

// SaveTranslation mocks base method.
func (m *MockAIService) SaveTranslation(ctx context.Context, entryID int64, isReadability bool, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTranslation", ctx, entryID, isReadability, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTranslation indicates an expected call of SaveTranslation.
func (mr *MockAIServiceMockRecorder) SaveTranslation(ctx, entryID, isReadability, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTranslation", reflect.TypeOf((*MockAIService)(nil).SaveTranslation), ctx, entryID, isReadability, content)
}

// Summarize mocks base method.
func (m *MockAIService) Summarize(ctx context.Context, entryID int64, content, title string, isReadability bool) (<-chan string, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", ctx, entryID, content, title, isReadability)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Summarize indicates an expected call of Summarize.
func (mr *MockAIServiceMockRecorder) Summarize(ctx, entryID, content, title, isReadability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockAIService)(nil).Summarize), ctx, entryID, content, title, isReadability)
}

// TranslateBatch mocks base method.
func (m *MockAIService) TranslateBatch(ctx context.Context, articles []service.BatchArticleInput) (<-chan service.BatchTranslateResult, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslateBatch", ctx, articles)
	ret0, _ := ret[0].(<-chan service.BatchTranslateResult)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TranslateBatch indicates an expected call of TranslateBatch.
func (mr *MockAIServiceMockRecorder) TranslateBatch(ctx, articles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateBatch", reflect.TypeOf((*MockAIService)(nil).TranslateBatch), ctx, articles)
}

// TranslateBlocks mocks base method.
func (m *MockAIService) TranslateBlocks(ctx context.Context, entryID int64, content, title string, isReadability bool) ([]service.TranslateBlockInfo, <-chan service.TranslateBlockResult, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslateBlocks", ctx, entryID, content, title, isReadability)
	ret0, _ := ret[0].([]service.TranslateBlockInfo)
	ret1, _ := ret[1].(<-chan service.TranslateBlockResult)
	ret2, _ := ret[2].(<-chan error)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// TranslateBlocks indicates an expected call of TranslateBlocks.
func (mr *MockAIServiceMockRecorder) TranslateBlocks(ctx, entryID, content, title, isReadability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateBlocks", reflect.TypeOf((*MockAIService)(nil).TranslateBlocks), ctx, entryID, content, title, isReadability)
}
