// Code generated by MockGen. DO NOT EDIT.
// Source: domain_rate_limit_service.go
//
// Generated by this command:
//
//	mockgen -source=domain_rate_limit_service.go -destination=mock/domain_rate_limit_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	service "gist/backend/internal/service"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDomainRateLimitService is a mock of DomainRateLimitService interface.
type MockDomainRateLimitService struct {
	ctrl     *gomock.Controller
	recorder *MockDomainRateLimitServiceMockRecorder
	isgomock struct{}
}

// MockDomainRateLimitServiceMockRecorder is the mock recorder for MockDomainRateLimitService.
type MockDomainRateLimitServiceMockRecorder struct {
	mock *MockDomainRateLimitService
}

// NewMockDomainRateLimitService creates a new mock instance.
func NewMockDomainRateLimitService(ctrl *gomock.Controller) *MockDomainRateLimitService {
	mock := &MockDomainRateLimitService{ctrl: ctrl}
	mock.recorder = &MockDomainRateLimitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainRateLimitService) EXPECT() *MockDomainRateLimitServiceMockRecorder {
	return m.recorder
}

// DeleteInterval mocks base method.
func (m *MockDomainRateLimitService) DeleteInterval(ctx context.Context, host string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInterval", ctx, host)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInterval indicates an expected call of DeleteInterval.
func (mr *MockDomainRateLimitServiceMockRecorder) DeleteInterval(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInterval", reflect.TypeOf((*MockDomainRateLimitService)(nil).DeleteInterval), ctx, host)
}

// GetInterval mocks base method.
func (m *MockDomainRateLimitService) GetInterval(ctx context.Context, host string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterval", ctx, host)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetInterval indicates an expected call of GetInterval.
func (mr *MockDomainRateLimitServiceMockRecorder) GetInterval(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterval", reflect.TypeOf((*MockDomainRateLimitService)(nil).GetInterval), ctx, host)
}

// GetIntervalDuration mocks base method.
func (m *MockDomainRateLimitService) GetIntervalDuration(ctx context.Context, host string) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntervalDuration", ctx, host)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetIntervalDuration indicates an expected call of GetIntervalDuration.
func (mr *MockDomainRateLimitServiceMockRecorder) GetIntervalDuration(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntervalDuration", reflect.TypeOf((*MockDomainRateLimitService)(nil).GetIntervalDuration), ctx, host)
}

// List mocks base method.
func (m *MockDomainRateLimitService) List(ctx context.Context) ([]service.DomainRateLimitDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]service.DomainRateLimitDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDomainRateLimitServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDomainRateLimitService)(nil).List), ctx)
}

// SetInterval mocks base method.
func (m *MockDomainRateLimitService) SetInterval(ctx context.Context, host string, seconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInterval", ctx, host, seconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInterval indicates an expected call of SetInterval.
func (mr *MockDomainRateLimitServiceMockRecorder) SetInterval(ctx, host, seconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInterval", reflect.TypeOf((*MockDomainRateLimitService)(nil).SetInterval), ctx, host, seconds)
}
