// Code generated by MockGen. DO NOT EDIT.
// Source: folder_service.go
//
// Generated by this command:
//
//	mockgen -source=folder_service.go -destination=mock/folder_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFolderService is a mock of FolderService interface.
type MockFolderService struct {
	ctrl     *gomock.Controller
	recorder *MockFolderServiceMockRecorder
	isgomock struct{}
}

// MockFolderServiceMockRecorder is the mock recorder for MockFolderService.
type MockFolderServiceMockRecorder struct {
	mock *MockFolderService
}

// NewMockFolderService creates a new mock instance.
func NewMockFolderService(ctrl *gomock.Controller) *MockFolderService {
	mock := &MockFolderService{ctrl: ctrl}
	mock.recorder = &MockFolderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFolderService) EXPECT() *MockFolderServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFolderService) Create(ctx context.Context, name string, parentID *int64, folderType string) (model.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, parentID, folderType)
	ret0, _ := ret[0].(model.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFolderServiceMockRecorder) Create(ctx, name, parentID, folderType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFolderService)(nil).Create), ctx, name, parentID, folderType)
}

// Delete mocks base method.
func (m *MockFolderService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFolderServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFolderService)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockFolderService) List(ctx context.Context) ([]model.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFolderServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFolderService)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockFolderService) Update(ctx context.Context, id int64, name string, parentID *int64) (model.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name, parentID)
	ret0, _ := ret[0].(model.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFolderServiceMockRecorder) Update(ctx, id, name, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFolderService)(nil).Update), ctx, id, name, parentID)
}

// UpdateType mocks base method.
func (m *MockFolderService) UpdateType(ctx context.Context, id int64, folderType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateType", ctx, id, folderType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateType indicates an expected call of UpdateType.
func (mr *MockFolderServiceMockRecorder) UpdateType(ctx, id, folderType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateType", reflect.TypeOf((*MockFolderService)(nil).UpdateType), ctx, id, folderType)
}
