// Code generated by MockGen. DO NOT EDIT.
// Source: icon_service.go
//
// Generated by this command:
//
//	mockgen -source=icon_service.go -destination=mock/icon_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIconService is a mock of IconService interface.
type MockIconService struct {
	ctrl     *gomock.Controller
	recorder *MockIconServiceMockRecorder
	isgomock struct{}
}

// MockIconServiceMockRecorder is the mock recorder for MockIconService.
type MockIconServiceMockRecorder struct {
	mock *MockIconService
}

// NewMockIconService creates a new mock instance.
func NewMockIconService(ctrl *gomock.Controller) *MockIconService {
	mock := &MockIconService{ctrl: ctrl}
	mock.recorder = &MockIconServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIconService) EXPECT() *MockIconServiceMockRecorder {
	return m.recorder
}

// BackfillIcons mocks base method.
func (m *MockIconService) BackfillIcons(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillIcons", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackfillIcons indicates an expected call of BackfillIcons.
func (mr *MockIconServiceMockRecorder) BackfillIcons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillIcons", reflect.TypeOf((*MockIconService)(nil).BackfillIcons), ctx)
}

// ClearAllIcons mocks base method.
func (m *MockIconService) ClearAllIcons(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAllIcons", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearAllIcons indicates an expected call of ClearAllIcons.
func (mr *MockIconServiceMockRecorder) ClearAllIcons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAllIcons", reflect.TypeOf((*MockIconService)(nil).ClearAllIcons), ctx)
}

// EnsureIcon mocks base method.
func (m *MockIconService) EnsureIcon(ctx context.Context, iconPath, siteURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureIcon", ctx, iconPath, siteURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIcon indicates an expected call of EnsureIcon.
func (mr *MockIconServiceMockRecorder) EnsureIcon(ctx, iconPath, siteURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIcon", reflect.TypeOf((*MockIconService)(nil).EnsureIcon), ctx, iconPath, siteURL)
}

// EnsureIconByFeedID mocks base method.
func (m *MockIconService) EnsureIconByFeedID(ctx context.Context, feedID int64, iconPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureIconByFeedID", ctx, feedID, iconPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIconByFeedID indicates an expected call of EnsureIconByFeedID.
func (mr *MockIconServiceMockRecorder) EnsureIconByFeedID(ctx, feedID, iconPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIconByFeedID", reflect.TypeOf((*MockIconService)(nil).EnsureIconByFeedID), ctx, feedID, iconPath)
}

// FetchAndSaveIcon mocks base method.
func (m *MockIconService) FetchAndSaveIcon(ctx context.Context, feedImageURL, siteURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAndSaveIcon", ctx, feedImageURL, siteURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAndSaveIcon indicates an expected call of FetchAndSaveIcon.
func (mr *MockIconServiceMockRecorder) FetchAndSaveIcon(ctx, feedImageURL, siteURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAndSaveIcon", reflect.TypeOf((*MockIconService)(nil).FetchAndSaveIcon), ctx, feedImageURL, siteURL)
}

// GetIconPath mocks base method.
func (m *MockIconService) GetIconPath(filename string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIconPath", filename)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIconPath indicates an expected call of GetIconPath.
func (mr *MockIconServiceMockRecorder) GetIconPath(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIconPath", reflect.TypeOf((*MockIconService)(nil).GetIconPath), filename)
}
