// Code generated by MockGen. DO NOT EDIT.
// Source: import_task.go
//
// Generated by this command:
//
//	mockgen -source=import_task.go -destination=mock/import_task.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImportTaskService is a mock of ImportTaskService interface.
type MockImportTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockImportTaskServiceMockRecorder
	isgomock struct{}
}

// MockImportTaskServiceMockRecorder is the mock recorder for MockImportTaskService.
type MockImportTaskServiceMockRecorder struct {
	mock *MockImportTaskService
}

// NewMockImportTaskService creates a new mock instance.
func NewMockImportTaskService(ctrl *gomock.Controller) *MockImportTaskService {
	mock := &MockImportTaskService{ctrl: ctrl}
	mock.recorder = &MockImportTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImportTaskService) EXPECT() *MockImportTaskServiceMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockImportTaskService) Cancel() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockImportTaskServiceMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockImportTaskService)(nil).Cancel))
}

// Complete mocks base method.
func (m *MockImportTaskService) Complete(result service.ImportResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Complete", result)
}

// Complete indicates an expected call of Complete.
func (mr *MockImportTaskServiceMockRecorder) Complete(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockImportTaskService)(nil).Complete), result)
}

// Fail mocks base method.
func (m *MockImportTaskService) Fail(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fail", err)
}

// Fail indicates an expected call of Fail.
func (mr *MockImportTaskServiceMockRecorder) Fail(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockImportTaskService)(nil).Fail), err)
}

// Get mocks base method.
func (m *MockImportTaskService) Get() *service.ImportTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*service.ImportTask)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockImportTaskServiceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockImportTaskService)(nil).Get))
}

// Start mocks base method.
func (m *MockImportTaskService) Start(total int) (string, context.Context) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", total)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(context.Context)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockImportTaskServiceMockRecorder) Start(total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockImportTaskService)(nil).Start), total)
}

// Update mocks base method.
func (m *MockImportTaskService) Update(current int, feed string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", current, feed)
}

// Update indicates an expected call of Update.
func (mr *MockImportTaskServiceMockRecorder) Update(current, feed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockImportTaskService)(nil).Update), current, feed)
}
