// Code generated by MockGen. DO NOT EDIT.
// Source: opml_service.go
//
// Generated by this command:
//
//	mockgen -source=opml_service.go -destination=mock/opml_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	service "gist/backend/internal/service"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOPMLService is a mock of OPMLService interface.
type MockOPMLService struct {
	ctrl     *gomock.Controller
	recorder *MockOPMLServiceMockRecorder
	isgomock struct{}
}

// MockOPMLServiceMockRecorder is the mock recorder for MockOPMLService.
type MockOPMLServiceMockRecorder struct {
	mock *MockOPMLService
}

// NewMockOPMLService creates a new mock instance.
func NewMockOPMLService(ctrl *gomock.Controller) *MockOPMLService {
	mock := &MockOPMLService{ctrl: ctrl}
	mock.recorder = &MockOPMLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOPMLService) EXPECT() *MockOPMLServiceMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockOPMLService) Export(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockOPMLServiceMockRecorder) Export(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockOPMLService)(nil).Export), ctx)
}

// Import mocks base method.
func (m *MockOPMLService) Import(ctx context.Context, reader io.Reader, onProgress func(service.ImportProgress)) (service.ImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, reader, onProgress)
	ret0, _ := ret[0].(service.ImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockOPMLServiceMockRecorder) Import(ctx, reader, onProgress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockOPMLService)(nil).Import), ctx, reader, onProgress)
}
