// Code generated by MockGen. DO NOT EDIT.
// Source: proxy_service.go
//
// Generated by this command:
//
//	mockgen -source=proxy_service.go -destination=mock/proxy_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProxyService is a mock of ProxyService interface.
type MockProxyService struct {
	ctrl     *gomock.Controller
	recorder *MockProxyServiceMockRecorder
	isgomock struct{}
}

// MockProxyServiceMockRecorder is the mock recorder for MockProxyService.
type MockProxyServiceMockRecorder struct {
	mock *MockProxyService
}

// NewMockProxyService creates a new mock instance.
func NewMockProxyService(ctrl *gomock.Controller) *MockProxyService {
	mock := &MockProxyService{ctrl: ctrl}
	mock.recorder = &MockProxyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyService) EXPECT() *MockProxyServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProxyService) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockProxyServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProxyService)(nil).Close))
}

// FetchImage mocks base method.
func (m *MockProxyService) FetchImage(ctx context.Context, imageURL, refererURL string) (*service.ProxyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchImage", ctx, imageURL, refererURL)
	ret0, _ := ret[0].(*service.ProxyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchImage indicates an expected call of FetchImage.
func (mr *MockProxyServiceMockRecorder) FetchImage(ctx, imageURL, refererURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchImage", reflect.TypeOf((*MockProxyService)(nil).FetchImage), ctx, imageURL, refererURL)
}
