// Code generated by MockGen. DO NOT EDIT.
// Source: readability_service.go
//
// Generated by this command:
//
//	mockgen -source=readability_service.go -destination=mock/readability_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReadabilityService is a mock of ReadabilityService interface.
type MockReadabilityService struct {
	ctrl     *gomock.Controller
	recorder *MockReadabilityServiceMockRecorder
	isgomock struct{}
}

// MockReadabilityServiceMockRecorder is the mock recorder for MockReadabilityService.
type MockReadabilityServiceMockRecorder struct {
	mock *MockReadabilityService
}

// NewMockReadabilityService creates a new mock instance.
func NewMockReadabilityService(ctrl *gomock.Controller) *MockReadabilityService {
	mock := &MockReadabilityService{ctrl: ctrl}
	mock.recorder = &MockReadabilityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadabilityService) EXPECT() *MockReadabilityServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockReadabilityService) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockReadabilityServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReadabilityService)(nil).Close))
}

// FetchReadableContent mocks base method.
func (m *MockReadabilityService) FetchReadableContent(ctx context.Context, entryID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchReadableContent", ctx, entryID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchReadableContent indicates an expected call of FetchReadableContent.
func (mr *MockReadabilityServiceMockRecorder) FetchReadableContent(ctx, entryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchReadableContent", reflect.TypeOf((*MockReadabilityService)(nil).FetchReadableContent), ctx, entryID)
}
