// Code generated by MockGen. DO NOT EDIT.
// Source: refresh_service.go
//
// Generated by this command:
//
//	mockgen -source=refresh_service.go -destination=mock/refresh_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshService is a mock of RefreshService interface.
type MockRefreshService struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshServiceMockRecorder
	isgomock struct{}
}

// MockRefreshServiceMockRecorder is the mock recorder for MockRefreshService.
type MockRefreshServiceMockRecorder struct {
	mock *MockRefreshService
}

// NewMockRefreshService creates a new mock instance.
func NewMockRefreshService(ctrl *gomock.Controller) *MockRefreshService {
	mock := &MockRefreshService{ctrl: ctrl}
	mock.recorder = &MockRefreshServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshService) EXPECT() *MockRefreshServiceMockRecorder {
	return m.recorder
}

// GetRefreshStatus mocks base method.
func (m *MockRefreshService) GetRefreshStatus() service.RefreshStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshStatus")
	ret0, _ := ret[0].(service.RefreshStatus)
	return ret0
}

// GetRefreshStatus indicates an expected call of GetRefreshStatus.
func (mr *MockRefreshServiceMockRecorder) GetRefreshStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshStatus", reflect.TypeOf((*MockRefreshService)(nil).GetRefreshStatus))
}

// IsRefreshing mocks base method.
func (m *MockRefreshService) IsRefreshing() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRefreshing")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRefreshing indicates an expected call of IsRefreshing.
func (mr *MockRefreshServiceMockRecorder) IsRefreshing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRefreshing", reflect.TypeOf((*MockRefreshService)(nil).IsRefreshing))
}

// RefreshAll mocks base method.
func (m *MockRefreshService) RefreshAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshAll indicates an expected call of RefreshAll.
func (mr *MockRefreshServiceMockRecorder) RefreshAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAll", reflect.TypeOf((*MockRefreshService)(nil).RefreshAll), ctx)
}

// RefreshFeed mocks base method.
func (m *MockRefreshService) RefreshFeed(ctx context.Context, feedID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshFeed", ctx, feedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshFeed indicates an expected call of RefreshFeed.
func (mr *MockRefreshServiceMockRecorder) RefreshFeed(ctx, feedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshFeed", reflect.TypeOf((*MockRefreshService)(nil).RefreshFeed), ctx, feedID)
}

// RefreshFeeds mocks base method.
func (m *MockRefreshService) RefreshFeeds(ctx context.Context, feedIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshFeeds", ctx, feedIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshFeeds indicates an expected call of RefreshFeeds.
func (mr *MockRefreshServiceMockRecorder) RefreshFeeds(ctx, feedIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshFeeds", reflect.TypeOf((*MockRefreshService)(nil).RefreshFeeds), ctx, feedIDs)
}
