// Code generated by MockGen. DO NOT EDIT.
// Source: ai_list_translation_repository.go
//
// Generated by this command:
//
//	mockgen -source=ai_list_translation_repository.go -destination=mock/ai_list_translation_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAIListTranslationRepository is a mock of AIListTranslationRepository interface.
type MockAIListTranslationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAIListTranslationRepositoryMockRecorder
	isgomock struct{}
}

// MockAIListTranslationRepositoryMockRecorder is the mock recorder for MockAIListTranslationRepository.
type MockAIListTranslationRepositoryMockRecorder struct {
	mock *MockAIListTranslationRepository
}

// NewMockAIListTranslationRepository creates a new mock instance.
func NewMockAIListTranslationRepository(ctrl *gomock.Controller) *MockAIListTranslationRepository {
	mock := &MockAIListTranslationRepository{ctrl: ctrl}
	mock.recorder = &MockAIListTranslationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIListTranslationRepository) EXPECT() *MockAIListTranslationRepositoryMockRecorder {
	return m.recorder
}

// DeleteAll mocks base method.
func (m *MockAIListTranslationRepository) DeleteAll(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockAIListTranslationRepositoryMockRecorder) DeleteAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockAIListTranslationRepository)(nil).DeleteAll), ctx)
}

// DeleteByEntryID mocks base method.
func (m *MockAIListTranslationRepository) DeleteByEntryID(ctx context.Context, entryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEntryID", ctx, entryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEntryID indicates an expected call of DeleteByEntryID.
func (mr *MockAIListTranslationRepositoryMockRecorder) DeleteByEntryID(ctx, entryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEntryID", reflect.TypeOf((*MockAIListTranslationRepository)(nil).DeleteByEntryID), ctx, entryID)
}

// Get mocks base method.
func (m *MockAIListTranslationRepository) Get(ctx context.Context, entryID int64, language string) (*model.AIListTranslation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, entryID, language)
	ret0, _ := ret[0].(*model.AIListTranslation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAIListTranslationRepositoryMockRecorder) Get(ctx, entryID, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAIListTranslationRepository)(nil).Get), ctx, entryID, language)
}

// GetBatch mocks base method.
func (m *MockAIListTranslationRepository) GetBatch(ctx context.Context, entryIDs []int64, language string) (map[int64]*model.AIListTranslation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatch", ctx, entryIDs, language)
	ret0, _ := ret[0].(map[int64]*model.AIListTranslation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatch indicates an expected call of GetBatch.
func (mr *MockAIListTranslationRepositoryMockRecorder) GetBatch(ctx, entryIDs, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatch", reflect.TypeOf((*MockAIListTranslationRepository)(nil).GetBatch), ctx, entryIDs, language)
}

// Save mocks base method.
func (m *MockAIListTranslationRepository) Save(ctx context.Context, entryID int64, language, title, summary string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entryID, language, title, summary)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAIListTranslationRepositoryMockRecorder) Save(ctx, entryID, language, title, summary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAIListTranslationRepository)(nil).Save), ctx, entryID, language, title, summary)
}
