// Code generated by MockGen. DO NOT EDIT.
// Source: ai_summary_repository.go
//
// Generated by this command:
//
//	mockgen -source=ai_summary_repository.go -destination=mock/ai_summary_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAISummaryRepository is a mock of AISummaryRepository interface.
type MockAISummaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAISummaryRepositoryMockRecorder
	isgomock struct{}
}

// MockAISummaryRepositoryMockRecorder is the mock recorder for MockAISummaryRepository.
type MockAISummaryRepositoryMockRecorder struct {
	mock *MockAISummaryRepository
}

// NewMockAISummaryRepository creates a new mock instance.
func NewMockAISummaryRepository(ctrl *gomock.Controller) *MockAISummaryRepository {
	mock := &MockAISummaryRepository{ctrl: ctrl}
	mock.recorder = &MockAISummaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAISummaryRepository) EXPECT() *MockAISummaryRepositoryMockRecorder {
	return m.recorder
}

// DeleteAll mocks base method.
func (m *MockAISummaryRepository) DeleteAll(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockAISummaryRepositoryMockRecorder) DeleteAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockAISummaryRepository)(nil).DeleteAll), ctx)
}

// DeleteByEntryID mocks base method.
func (m *MockAISummaryRepository) DeleteByEntryID(ctx context.Context, entryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEntryID", ctx, entryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEntryID indicates an expected call of DeleteByEntryID.
func (mr *MockAISummaryRepositoryMockRecorder) DeleteByEntryID(ctx, entryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEntryID", reflect.TypeOf((*MockAISummaryRepository)(nil).DeleteByEntryID), ctx, entryID)
}

// Get mocks base method.
func (m *MockAISummaryRepository) Get(ctx context.Context, entryID int64, isReadability bool, language string) (*model.AISummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, entryID, isReadability, language)
	ret0, _ := ret[0].(*model.AISummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAISummaryRepositoryMockRecorder) Get(ctx, entryID, isReadability, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAISummaryRepository)(nil).Get), ctx, entryID, isReadability, language)
}

// Save mocks base method.
func (m *MockAISummaryRepository) Save(ctx context.Context, entryID int64, isReadability bool, language, summary string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entryID, isReadability, language, summary)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAISummaryRepositoryMockRecorder) Save(ctx, entryID, isReadability, language, summary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAISummaryRepository)(nil).Save), ctx, entryID, isReadability, language, summary)
}
