// Code generated by MockGen. DO NOT EDIT.
// Source: ai_translation_repository.go
//
// Generated by this command:
//
//	mockgen -source=ai_translation_repository.go -destination=mock/ai_translation_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAITranslationRepository is a mock of AITranslationRepository interface.
type MockAITranslationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAITranslationRepositoryMockRecorder
	isgomock struct{}
}

// MockAITranslationRepositoryMockRecorder is the mock recorder for MockAITranslationRepository.
type MockAITranslationRepositoryMockRecorder struct {
	mock *MockAITranslationRepository
}

// NewMockAITranslationRepository creates a new mock instance.
func NewMockAITranslationRepository(ctrl *gomock.Controller) *MockAITranslationRepository {
	mock := &MockAITranslationRepository{ctrl: ctrl}
	mock.recorder = &MockAITranslationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAITranslationRepository) EXPECT() *MockAITranslationRepositoryMockRecorder {
	return m.recorder
}

// DeleteAll mocks base method.
func (m *MockAITranslationRepository) DeleteAll(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockAITranslationRepositoryMockRecorder) DeleteAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockAITranslationRepository)(nil).DeleteAll), ctx)
}

// DeleteByEntryID mocks base method.
func (m *MockAITranslationRepository) DeleteByEntryID(ctx context.Context, entryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEntryID", ctx, entryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEntryID indicates an expected call of DeleteByEntryID.
func (mr *MockAITranslationRepositoryMockRecorder) DeleteByEntryID(ctx, entryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEntryID", reflect.TypeOf((*MockAITranslationRepository)(nil).DeleteByEntryID), ctx, entryID)
}

// Get mocks base method.
func (m *MockAITranslationRepository) Get(ctx context.Context, entryID int64, isReadability bool, language string) (*model.AITranslation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, entryID, isReadability, language)
	ret0, _ := ret[0].(*model.AITranslation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAITranslationRepositoryMockRecorder) Get(ctx, entryID, isReadability, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAITranslationRepository)(nil).Get), ctx, entryID, isReadability, language)
}

// Save mocks base method.
func (m *MockAITranslationRepository) Save(ctx context.Context, entryID int64, isReadability bool, language, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entryID, isReadability, language, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAITranslationRepositoryMockRecorder) Save(ctx, entryID, isReadability, language, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAITranslationRepository)(nil).Save), ctx, entryID, isReadability, language, content)
}
