// Code generated by MockGen. DO NOT EDIT.
// Source: domain_rate_limit_repository.go
//
// Generated by this command:
//
//	mockgen -source=domain_rate_limit_repository.go -destination=mock/domain_rate_limit_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDomainRateLimitRepository is a mock of DomainRateLimitRepository interface.
type MockDomainRateLimitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDomainRateLimitRepositoryMockRecorder
	isgomock struct{}
}

// MockDomainRateLimitRepositoryMockRecorder is the mock recorder for MockDomainRateLimitRepository.
type MockDomainRateLimitRepositoryMockRecorder struct {
	mock *MockDomainRateLimitRepository
}

// NewMockDomainRateLimitRepository creates a new mock instance.
func NewMockDomainRateLimitRepository(ctrl *gomock.Controller) *MockDomainRateLimitRepository {
	mock := &MockDomainRateLimitRepository{ctrl: ctrl}
	mock.recorder = &MockDomainRateLimitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainRateLimitRepository) EXPECT() *MockDomainRateLimitRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDomainRateLimitRepository) Create(ctx context.Context, host string, intervalSeconds int) (*model.DomainRateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, host, intervalSeconds)
	ret0, _ := ret[0].(*model.DomainRateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDomainRateLimitRepositoryMockRecorder) Create(ctx, host, intervalSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDomainRateLimitRepository)(nil).Create), ctx, host, intervalSeconds)
}

// Delete mocks base method.
func (m *MockDomainRateLimitRepository) Delete(ctx context.Context, host string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, host)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDomainRateLimitRepositoryMockRecorder) Delete(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDomainRateLimitRepository)(nil).Delete), ctx, host)
}

// GetByHost mocks base method.
func (m *MockDomainRateLimitRepository) GetByHost(ctx context.Context, host string) (*model.DomainRateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHost", ctx, host)
	ret0, _ := ret[0].(*model.DomainRateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHost indicates an expected call of GetByHost.
func (mr *MockDomainRateLimitRepositoryMockRecorder) GetByHost(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHost", reflect.TypeOf((*MockDomainRateLimitRepository)(nil).GetByHost), ctx, host)
}

// List mocks base method.
func (m *MockDomainRateLimitRepository) List(ctx context.Context) ([]model.DomainRateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.DomainRateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDomainRateLimitRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDomainRateLimitRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockDomainRateLimitRepository) Update(ctx context.Context, host string, intervalSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, host, intervalSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDomainRateLimitRepositoryMockRecorder) Update(ctx, host, intervalSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDomainRateLimitRepository)(nil).Update), ctx, host, intervalSeconds)
}
