// Code generated by MockGen. DO NOT EDIT.
// Source: folder_repository.go
//
// Generated by this command:
//
//	mockgen -source=folder_repository.go -destination=mock/folder_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFolderRepository is a mock of FolderRepository interface.
type MockFolderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFolderRepositoryMockRecorder
	isgomock struct{}
}

// MockFolderRepositoryMockRecorder is the mock recorder for MockFolderRepository.
type MockFolderRepositoryMockRecorder struct {
	mock *MockFolderRepository
}

// NewMockFolderRepository creates a new mock instance.
func NewMockFolderRepository(ctrl *gomock.Controller) *MockFolderRepository {
	mock := &MockFolderRepository{ctrl: ctrl}
	mock.recorder = &MockFolderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFolderRepository) EXPECT() *MockFolderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFolderRepository) Create(ctx context.Context, name string, parentID *int64, folderType string) (model.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, parentID, folderType)
	ret0, _ := ret[0].(model.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFolderRepositoryMockRecorder) Create(ctx, name, parentID, folderType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFolderRepository)(nil).Create), ctx, name, parentID, folderType)
}

// Delete mocks base method.
func (m *MockFolderRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFolderRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFolderRepository)(nil).Delete), ctx, id)
}

// FindByName mocks base method.
func (m *MockFolderRepository) FindByName(ctx context.Context, name string, parentID *int64) (*model.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name, parentID)
	ret0, _ := ret[0].(*model.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockFolderRepositoryMockRecorder) FindByName(ctx, name, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockFolderRepository)(nil).FindByName), ctx, name, parentID)
}

// GetByID mocks base method.
func (m *MockFolderRepository) GetByID(ctx context.Context, id int64) (model.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFolderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFolderRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockFolderRepository) List(ctx context.Context) ([]model.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFolderRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFolderRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockFolderRepository) Update(ctx context.Context, id int64, name string, parentID *int64) (model.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name, parentID)
	ret0, _ := ret[0].(model.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFolderRepositoryMockRecorder) Update(ctx, id, name, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFolderRepository)(nil).Update), ctx, id, name, parentID)
}

// UpdateType mocks base method.
func (m *MockFolderRepository) UpdateType(ctx context.Context, id int64, folderType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateType", ctx, id, folderType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateType indicates an expected call of UpdateType.
func (mr *MockFolderRepositoryMockRecorder) UpdateType(ctx, id, folderType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateType", reflect.TypeOf((*MockFolderRepository)(nil).UpdateType), ctx, id, folderType)
}
